export default function getData() {
  return {
    web3: [
      { domain: "1stchoiceleasing.888", categories: ["HOUSING & REAL ESTATE"] },
      {
        domain: "1stchoicerentals.888",
        categories: ["HOUSING & REAL ESTATE", "CRYPTO"],
      },
      { domain: "420break.888", categories: ["MARIJUANA"] },
      { domain: "4lease.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "5starresort.888", categories: ["VACATIONS"] },
      { domain: "5starresorts.888", categories: ["VACATIONS"] },
      { domain: "5starvacation.888", categories: ["VACATIONS"] },
      { domain: "5starvacations.888", categories: ["VACATIONS"] },
      { domain: "5starvegas.888", categories: ["VACATIONS"] },
      { domain: "7-eleven-stores.888", categories: ["RETAIL"] },
      {
        domain: "affordablerentals.888",
        categories: ["HOUSING & REAL ESTATE"],
      },
      { domain: "allelectricauto.888", categories: ["AUTOMOBILE"] },
      { domain: "allelectricautos.888", categories: ["AUTOMOBILE"] },
      { domain: "allelectriccars.888", categories: ["AUTOMOBILE"] },
      { domain: "allelectrictruck.888", categories: ["AUTOMOBILE"] },
      { domain: "allelectrictrucks.888", categories: ["AUTOMOBILE"] },
      { domain: "allelectricvehicles.888", categories: ["AUTOMOBILE"] },
      { domain: "anonyverse.888", categories: ["CRYPTO"] },
      { domain: "apartments4lease.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "aptrental.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "aptrentals.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "apts4lease.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "apts4rent.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "attorney-at-law.888", categories: ["LAW & ORDER"] },
      { domain: "autoautos.888", categories: ["AUTOMOBILE"] },
      { domain: "autonomousauto.888", categories: ["AUTOMOBILE"] },
      { domain: "autonomousautos.888", categories: ["AUTOMOBILE"] },
      { domain: "autonomouscar.888", categories: ["AUTOMOBILE"] },
      { domain: "autonomouscars.888", categories: ["AUTOMOBILE"] },
      { domain: "autonomoustrucks.888", categories: ["AUTOMOBILE"] },
      { domain: "autos4rent.888", categories: ["AUTOMOBILE"] },
      { domain: "av-auto.888", categories: ["AUTOMOBILE"] },
      { domain: "av-autos.888", categories: ["AUTOMOBILE"] },
      { domain: "av-cars.888", categories: ["AUTOMOBILE"] },
      { domain: "av-truck.888", categories: ["AUTOMOBILE"] },
      { domain: "av-trucks.888", categories: ["AUTOMOBILE"] },
      { domain: "av-vehicle.888", categories: ["AUTOMOBILE"] },
      { domain: "av-vehicles.888", categories: ["AUTOMOBILE"] },
      {
        domain: "beachfrontestates.888",
        categories: ["HOUSING & REAL ESTATE"],
      },
      { domain: "bestvegasresort.888", categories: ["VACATIONS"] },
      { domain: "burgerandfries.888", categories: ["FOOD"] },
      { domain: "businesslawyer.888", categories: ["LAW & ORDER"] },
      { domain: "cars4rent.888", categories: ["AUTOMOBILE"] },
      { domain: "casinometa.888", categories: ["CRYPTO", "GAMBLING"] },
      { domain: "clickit.888", categories: ["DOMAIN"] },
      { domain: "clickpay.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "cometojamaica.888", categories: ["VACATIONS"] },
      {
        domain: "complaintsdepartment.888",
        categories: ["BUSINESS & FINANCE"],
      },
      { domain: "complaintsdept.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "credit-bureau.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "creditcollection.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "criminaldefense.888", categories: ["LAW & ORDER"] },
      { domain: "cryptobullish.888", categories: ["CRYPTO"] },
      { domain: "cryptogreed.888", categories: ["CRYPTO"] },
      { domain: "cryptoperpetuals.888", categories: ["CRYPTO"] },
      { domain: "cryptorobots.888", categories: ["CRYPTO"] },
      { domain: "cuckclub.888", categories: ["ADULT"] },
      { domain: "cuckhub.888", categories: ["ADULT"] },
      { domain: "cuckoldclub.888", categories: ["ADULT"] },
      { domain: "cuckoldsex.888", categories: ["ADULT"] },
      { domain: "cuckquean.888", categories: ["ADULT"] },
      {
        domain: "customerservicedepartment.888",
        categories: ["BUSINESS & FINANCE"],
      },
      { domain: "customerservicedept.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "cybersecuritycareers.888", categories: ["JOBS & CAREERS"] },
      { domain: "cybersecurityjobs.888", categories: ["JOBS & CAREERS"] },
      { domain: "davesmith.888", categories: ["PERSONAL"] },
      { domain: "digitalcanvas.888", categories: ["GAMING"] },
      { domain: "domainappraisals.888", categories: ["DOMAIN"] },
      { domain: "domainbuy.888", categories: ["DOMAIN"] },
      { domain: "domainlease.888", categories: ["DOMAIN"] },
      { domain: "domainleasing.888", categories: ["DOMAIN"] },
      { domain: "domainrent.888", categories: ["DOMAIN"] },
      { domain: "domains4lease.888", categories: ["DOMAIN"] },
      { domain: "domains4rent.888", categories: ["DOMAIN"] },
      { domain: "domainsales.888", categories: ["DOMAIN"] },
      { domain: "domainsell.888", categories: ["DOMAIN"] },
      { domain: "domainsforlease.888", categories: ["DOMAIN"] },
      { domain: "domainsforrent.888", categories: ["DOMAIN"] },
      { domain: "dontbehatin.888", categories: ["PERSONAL"] },
      { domain: "donthate.888", categories: ["PERSONAL"] },
      { domain: "dopedealer.888", categories: ["MARIJUANA"] },
      { domain: "easyloan.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "ecorporateoffices.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "electricauto.888", categories: ["AUTOMOBILE"] },
      { domain: "electricautos.888", categories: ["AUTOMOBILE"] },
      { domain: "elitenft.888", categories: ["CRYPTO"] },
      { domain: "elitenfts.888", categories: ["CRYPTO"] },
      { domain: "estatelawyer.888", categories: ["LAW & ORDER"] },
      { domain: "fartface.888", categories: ["HUMOROUS"] },
      { domain: "fartsarefunny.888", categories: ["HUMOROUS"] },
      { domain: "fastfooddelivery.888", categories: ["FOOD"] },
      { domain: "findnft.888", categories: ["CRYPTO"] },
      { domain: "findnfts.888", categories: ["CRYPTO"] },
      { domain: "finestvegas.888", categories: ["VACATIONS"] },
      { domain: "flytojamaica.888", categories: ["VACATIONS"] },
      { domain: "footwearfashions.888", categories: ["RETAIL"] },
      { domain: "forlease.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "for-rent.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "freehomedelivery.888", categories: ["RETAIL"] },
      { domain: "funnyfarts.888", categories: ["HUMOROUS"] },
      { domain: "gamblemeta.888", categories: ["CRYPTO", "GAMBLING"] },
      { domain: "gamblevegas.888", categories: ["CRYPTO", "GAMBLING"] },
      { domain: "gamerzone.888", categories: ["GAMING"] },
      { domain: "gentlemansclub.888", categories: ["ADULT"] },
      { domain: "getitnow.888", categories: ["RETAIL"] },
      { domain: "grocerydelivery.888", categories: ["RETAIL"] },
      { domain: "healthypet.888", categories: ["PETS"] },
      { domain: "healthypetfood.888", categories: ["PETS"] },
      { domain: "healthypets.888", categories: ["PETS"] },
      { domain: "hellsangel.888", categories: ["GANGSTER"] },
      { domain: "hiphopproducer.888", categories: ["MUSIC"] },
      { domain: "hotproduct.888", categories: ["RETAIL"] },
      { domain: "houses4lease.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "houses4rent.888", categories: ["HOUSING & REAL ESTATE"] },
      {
        domain: "humanresourcesdepartment.888",
        categories: ["BUSINESS & FINANCE"],
      },
      { domain: "humanresourcesdept.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "impaying.888", categories: ["RETAIL", "BUSINESS & FINANCE"] },
      { domain: "indicators.888", categories: ["CRYPTO"] },
      { domain: "iriejamaica.888", categories: ["VACATIONS"] },
      { domain: "isupport81.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "itsshowtime.888", categories: ["RANDOM"] },
      { domain: "itstime.888", categories: ["RANDOM"] },
      { domain: "jamaicangirls.888", categories: ["ADULT"] },
      { domain: "jamaicanpussy.888", categories: ["ADULT"] },
      { domain: "jamaicatourism.888", categories: ["VACATIONS"] },
      { domain: "jamaicatours.888", categories: ["VACATIONS"] },
      { domain: "jiffypay.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "jimjohnson.888", categories: ["PERSONAL"] },
      { domain: "johnnysmith.888", categories: ["PERSONAL"] },
      { domain: "j-smith.888", categories: ["PERSONAL"] },
      { domain: "lasvegastours.888", categories: ["VACATIONS"] },
      { domain: "leasedomain.888", categories: ["DOMAIN"] },
      { domain: "leasedomains.888", categories: ["DOMAIN"] },
      { domain: "lease-it.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "lobstertail.888", categories: ["FOOD"] },
      { domain: "localhomedelivery.888", categories: ["RETAIL"] },
      { domain: "localmd.888", categories: ["HEALTH"] },
      { domain: "luxuryapts.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "luxurylifestyles.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "masonictemple.888", categories: ["RANDOM"] },
      { domain: "medicalsurgeon.888", categories: ["HEALTH"] },
      { domain: "metachamp.888", categories: ["CRYPTO"] },
      { domain: "metachampion.888", categories: ["CRYPTO"] },
      { domain: "metacrave.888", categories: ["CRYPTO"] },
      { domain: "metacraving.888", categories: ["CRYPTO"] },
      { domain: "metacraze.888", categories: ["CRYPTO"] },
      { domain: "metacrazy.888", categories: ["CRYPTO"] },
      { domain: "metadiner.888", categories: ["CRYPTO"] },
      { domain: "metadiscount.888", categories: ["CRYPTO"] },
      { domain: "metafag.888", categories: ["ADULT"] },
      { domain: "metafags.888", categories: ["ADULT"] },
      { domain: "metafremont.888", categories: ["CRYPTO"] },
      { domain: "metamilf.888", categories: ["ADULT"] },
      { domain: "metamilfs.888", categories: ["ADULT"] },
      { domain: "metapills.888", categories: ["PHARMACEUTICALS"] },
      { domain: "metaqueer.888", categories: ["ADULT"] },
      { domain: "metaqueers.888", categories: ["ADULT"] },
      { domain: "metawiki.888", categories: ["CRYPTO"] },
      { domain: "metawinner.888", categories: ["CRYPTO"] },
      { domain: "metawinning.888", categories: ["CRYPTO"] },
      { domain: "metawins.888", categories: ["CRYPTO"] },
      { domain: "milfantasy.888", categories: ["ADULT"] },
      { domain: "milfaverse.888", categories: ["ADULT"] },
      { domain: "milfshake.888", categories: ["ADULT"] },
      { domain: "moderndaygangsta.888", categories: ["GANGSTER"] },
      { domain: "montegojamaica.888", categories: ["VACATIONS"] },
      { domain: "morningcoffee.888", categories: ["FOOD"] },
      { domain: "nftgamingzone.888", categories: ["GAMING"] },
      { domain: "nftpick.888", categories: ["CRYPTO"] },
      { domain: "nftpicks.888", categories: ["CRYPTO"] },
      { domain: "oldschoolgangsta.888", categories: ["GANGSTER"] },
      { domain: "oldschoolgangster.888", categories: ["GANGSTER"] },
      { domain: "onlineorders.888", categories: ["RETAIL"] },
      { domain: "orderitonline.888", categories: ["RETAIL"] },
      { domain: "originalgangsta.888", categories: ["GANGSTER"] },
      { domain: "pharmaweb.888", categories: ["PHARMACEUTICALS"] },
      { domain: "potforsale.888", categories: ["MARIJUANA"] },
      { domain: "primeproperties.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "promusicproduction.888", categories: ["MUSIC"] },
      { domain: "prontopay.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "proreno.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "prorenos.888", categories: ["HOUSING & REAL ESTATE"] },
      { domain: "qualitypetfood.888", categories: ["PETS"] },
      { domain: "rentdomain.888", categories: ["DOMAIN"] },
      { domain: "rentdomains.888", categories: ["DOMAIN"] },
      { domain: "retailfranchises.888", categories: ["RETAIL"] },
      { domain: "self-drivingauto.888", categories: ["AUTOMOBILE"] },
      { domain: "self-drivingautos.888", categories: ["AUTOMOBILE"] },
      { domain: "selfdrivingcar.888", categories: ["AUTOMOBILE"] },
      { domain: "self-drivingcars.888", categories: ["AUTOMOBILE"] },
      { domain: "selfdrivingcars.888", categories: ["AUTOMOBILE"] },
      { domain: "self-drivingtrucks.888", categories: ["AUTOMOBILE"] },
      { domain: "self-drivingvehicle.888", categories: ["AUTOMOBILE"] },
      { domain: "self-drivingvehicles.888", categories: ["AUTOMOBILE"] },
      { domain: "selldomains.888", categories: ["DOMAIN"] },
      { domain: "shawarmas.888", categories: ["FOOD"] },
      { domain: "sincitynevada.888", categories: ["VACATIONS"] },
      { domain: "smartcontractdeveloper.888", categories: ["CRYPTO"] },
      { domain: "smellyfarts.888", categories: ["HUMOROUS"] },
      { domain: "smokecannabis.888", categories: ["MARIJUANA"] },
      { domain: "snappypay.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "sportsgaming.888", categories: ["GAMING"] },
      { domain: "stinkyfarts.888", categories: ["HUMOROUS"] },
      { domain: "support81.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "thevegasstrip.888", categories: ["VACATIONS"] },
      { domain: "top10cryptos.888", categories: ["CRYPTO"] },
      { domain: "top10nfts.888", categories: ["CRYPTO"] },
      { domain: "top20cryptos.888", categories: ["CRYPTO"] },
      { domain: "top20nfts.888", categories: ["CRYPTO"] },
      { domain: "top5nft.888", categories: ["CRYPTO"] },
      { domain: "top5nfts.888", categories: ["CRYPTO"] },
      { domain: "trucks4lease.888", categories: ["AUTOMOBILE"] },
      { domain: "trucks4rent.888", categories: ["AUTOMOBILE"] },
      { domain: "underwriters.888", categories: ["BUSINESS & FINANCE"] },
      { domain: "utilitynft.888", categories: ["CRYPTO"] },
      { domain: "vegasentertainment.888", categories: ["VACATIONS"] },
      { domain: "vegasescortservice.888", categories: ["VACATIONS"] },
      { domain: "vegaslive.888", categories: ["VACATIONS"] },
      { domain: "vegasparty.888", categories: ["VACATIONS"] },
      { domain: "vegasshowgirls.888", categories: ["VACATIONS"] },
      { domain: "vegasshowtickets.888", categories: ["VACATIONS"] },
      { domain: "vegastourguides.888", categories: ["VACATIONS"] },
      { domain: "vivavegas.888", categories: ["VACATIONS"] },
      { domain: "wannapay.888", categories: ["RETAIL", "BUSINESS & FINANCE"] },
      {
        domain: "web3cloudengineeringsystems.888",
        categories: ["DOMAIN", "CRYPTO"],
      },
      {
        domain: "web3enterprisesoftware.888",
        categories: ["DOMAIN", "CRYPTO"],
      },
      { domain: "web3md.888", categories: ["DOMAIN", "CRYPTO"] },
      { domain: "web3oracles.888", categories: ["DOMAIN", "CRYPTO"] },
    ],
    web2: [
      "1ofakindnfts.com",
      "1stchoicecryptos.com",
      "1stclasscryptos.com",
      "3dmetaclay.xyz",
      "3dmetamodels.xyz",
      "3dmetaprinting.xyz",
      "3dmetaversemodels.xyz",
      "3dmodelverse.xyz",
      "3dprime.xyz",
      "3dprintaverse.xyz",
      "3dreal.xyz",
      "3drealmodels.xyz",
      "auctionblockchaindomains.com",
      "auctionnftdomain.com",
      "auctionnftdomains.com",
      "blockchaindomainauction.com",
      "crypto-trading-indicator.com",
      "crypto-trading-indicators.com",
      "cryptocartrader.com",
      "cryptofuturestraders.com",
      "cryptogame4cash.com",
      "cryptogamescash.com",
      "cryptogamesforcash.com",
      "cryptogamesgod.com",
      "cryptogamestoken.com",
      "cryptogaming4cash.com",
      "cryptogaming4cash.net",
      "cryptogaming4cash.org",
      "cryptogamingcash.com",
      "cryptogamingforcash.com",
      "cryptogaminggod.com",
      "cryptometagaming.com",
      "cryptonewsnightly.com",
      "cryptonewsstory.com",
      "cryptosportgames.com",
      "cryptosportinggames.com",
      "cryptosportsgames.com",
      "cryptotraderoptions.com",
      "currentmetanews.com",
      "currentmetaproject.com",
      "currentmetaprojects.com",
      "currentmetaversenews.com",
      "digimodel.xyz",
      "digimodels.xyz",
      "digitalmodels.xyz",
      "dirtygirlsnft.com",
      "dirtygirlsnfts.com",
      "dirtywomennft.com",
      "dirtywomennfts.com",
      "domainkings.xyz",
      "domainsalesleasing.com",
      "web3onboarding.com",
      "web3onboarding.com",
      "web3onboarding.com",
      "web3onboarding.com",
      "web3onboarding.com",
      "web3onboarding.com",
      "faultlessnft.com",
      "faultlessnfts.com",
      "gamingcryptocash.com",
      "gamingwinscrypto.com",
      "getweb3domain.com",
      "getweb3domains.com",
      "goliathnfts.com",
      "highdemandnft.com",
      "highdemandnfts.com",
      "highreturncrypto.com",
      "highreturncryptos.com",
      "highreturnyieldfarm.com",
      "highreturnyieldfarms.com",
      "highriskhighrewards.com",
      "highriskyieldfarm.com",
      "highriskyieldfarming.com",
      "highriskyieldfarms.com",
      "highyieldcryptos.com",
      "imtokenized.com",
      "incomparablenft.com",
      "incomparablenfts.com",
      "iso20022cryptos.com",
      "iso20022now.com",
      "kookooforcrypto.com",
      "leaseweb3domain.com",
      "leaseweb3domains.com",
      "lowrisklowreward.com",
      "lowriskyieldfarm.com",
      "lowriskyieldfarming.com",
      "lowriskyieldfarms.com",
      "luxuryretirementcondos.com",
      "matchlessnfts.com",
      "metacashmachines.com",
      "metaclay.xyz",
      "metaclay3d.xyz",
      "metagamblinggod.com",
      "metagamesgod.com",
      "metagaminggeek.com",
      "metagaminggod.com",
      "metagaminggod.win",
      "metagaminggod.xyz",
      "metagaminggods.com",
      "metagamingplay.com",
      "metagoldmachine.com",
      "metagoldmachines.com",
      "metanftmachine.com",
      "metanftmachines.com",
      "metaprime3d.xyz",
      "metaprimemodels.xyz",
      "metaversegamerzone.com",
      "metavision3d.xyz",
      "milftokens.com",
      "modelversal.xyz",
      "mymetacashmachine.com",
      "mymetacashmachines.com",
      "nftdomainbroker.co",
      "nftdomainbrokers.co",
      "nftdomainbrokers.com",
      "nftdomaincraze.com",
      "nftdomainforlease.com",
      "nftdomainforrent.com",
      "nftdomainmania.com",
      "nftdomainsforlease.com",
      "nftdomainsforrent.com",
      "nftgoliaths.com",
      "nftprotrading.com",
      "nftswapmart.com",
      "nightlycryptonews.com",
      "oneandonlynfts.com",
      "outstandingnfts.com",
      "phatcryptos.com",
      "phatcryptowallet.com",
      "phatcryptowallets.com",
      "pkex.exchange",
      "premium3d.xyz",
      "prime3d.xyz",
      "primemodel.xyz",
      "printaverse.xyz",
      "real3dmodels.xyz",
      "realmodel.xyz",
      "realmodels.xyz",
      "realvision3d.xyz",
      "rectifywalletissues.com",
      "rentalhousinghub.com",
      "rentblockchaindomain.com",
      "rentblockchaindomains.com",
      "rentnftdomains.com",
      "rentweb3domain.com",
      "rentweb3domains.com",
      "residentialconcretejobs.ca",
      "residentialconcretejobs.com",
      "restoracrete.ca",
      "secondtononenft.com",
      "secondtononenfts.com",
      "sellweb3domain.com",
      "sellweb3domains.com",
      "sluttokens.com",
      "stakesavior.com",
      "stakesaviors.com",
      "stakesaviours.com",
      "studentapartmenthub.com",
      "studentapthub.com",
      "studentaptleasing.com",
      "studentaptrental.com",
      "studentaptrentals.com",
      "studentboardinghouse.com",
      "studentboardinghouses.com",
      "studentdormrentals.com",
      "studentrentalapts.com",
      "studentrentalrooms.com",
      "studentroomandboard.com",
      "studentsharedhousing.com",
      "toptrendingcryptos.com",
      "toptrendingnft.com",
      "toptrendingnfts.com",
      "tradingcryptooptions.com",
      "undisputednfts.com",
      "unequalednft.com",
      "unequalednfts.com",
      "unmatchednft.com",
      "unmatchednfts.com",
      "unquestionablenft.com",
      "unquestionablenfts.com",
      "unrivalednfts.com",
      "urtokenized.com",
      "virtualmodels.xyz",
      "virtuamodel.xyz",
      "virtuamodels.xyz",
      "walletfixers.com",
      "web3forlease.com",
      "web3forrent.com",
      "whoretokens.com",
    ],
  };
}
